Enhance UI (~3830)
simplic/simplic-service-platform pull request #12
Opened 2022-12-23 13:28 UTC by MattisBergmann

- Adds a searchbar to search for AppServers
- Adds buttons to collapse/expand all AppServer cards

![image](https://user-images.githubusercontent.com/102026036/209343812-4d307747-dc23-4173-ac44-acea7d3fa151.png)

2023-01-04 08:12 UTC, NexQueek approved these changes

2023-01-04 08:12 UTC, NexQueek commented on release-notes.xml
> +    <Change type="enhancement">Adds buttons to collapse/expand all AppServers int the AppServer modules view</Change>
missing dot at the end of the sentence

2023-01-09 09:19 UTC, MEichhoff requested changes

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.1.1722.412")]
Usually the pipeline should set new version numbers

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +    public delegate void CollapseEventHandler(object sender, CollapseEventArgs args);
The delegate should not be definded directly in the namespace

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +    public class CollapseEventArgs : EventArgs
missing comment and also each class should be in its own file

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +                servicesToRemove.Add(new ServiceDefinitionViewModel(SelectedServiceCard.Model, this));
Instead of using the servicesToRemove stuff you could use a statefull collection behind the observable collection and go through the states in the save/close method

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
> +                Text = "Expand All",
Use localization instead

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
> +                Text = "Collapse All",
Use localization instead

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
>                  Text = "Remove",
Use localization instead

2023-01-09 09:19 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
>                  Text = "Add",
Use localization instead

2023-01-11 14:24 UTC, mergmann commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
> +                Text = "Expand All",
There is already a "TextLocalizationKey" set, which will override the "Text"

2023-01-26 06:00 UTC, MEichhoff requested changes

2023-01-26 06:00 UTC, MEichhoff commented on release-notes.xml
> +    <Change type="enhancement">Adds buttons to collapse/expand all AppServers int the AppServer modules view.</Change>
```suggestion
    <Change type="enhancement">Adds buttons to collapse/expand all AppServers in the AppServer modules view.</Change>
```

2023-01-26 06:00 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/CollapseEventArgs.cs
> +    }
```suggestion
        public ServiceDefinitionViewModel Service { get; set; }
    }
```

2023-01-26 06:00 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/CollapseEventArgs.cs
> +        public ServiceDefinitionViewModel Service { get; set; }
comments

2023-01-26 06:00 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +        public delegate void CollapseEventHandler(object sender, CollapseEventArgs args);
Respect the order of elements in a class. Delegates should be between the construcotor and methods

2023-03-22 07:05 UTC, MEichhoff approved these changes

2023-03-27 13:21 UTC, merged