F service platform UI
simplic/simplic-service-platform pull request #2
Opened 2022-03-08 16:12 UTC by 4eck-qed

Depends on new localization keys.

2022-03-18 10:25 UTC, MEichhoff requested changes
Also include a screenshot of the ui

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.PlugIn.ServicePlatform.Client/packages.config
> +</packages>
migrate package config. This is a context menu function in visual studio. After the migration installed packages will be referenced as nuget reference and not in a seperate file

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.Data.DB/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.3421.1230")]
usually you should use the pipeline to increase the version number and not push the version of your local nuget manager

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Behaviors/CopyItemDragDropBehavior.cs
> +}
is this still required wenn it does not do anything?

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Behaviors/UniqueServiceModuleDragDropBehavior.cs
> +                MessageBox.Show(CommonServiceLocator.ServiceLocator.Current.GetInstance<ILocalizationService>().Translate("validation_already_exists", draggedModule?.Model.Name));
use the localized message box instead.

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Behaviors/UniqueServiceModuleDragDropBehavior.cs
> +        public override void Drop(DragDropState state)
all public things should have comments

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Converters/ModuleDataConverter.cs
> +using System.Text;
remove unnecessary usings

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Converters/ModuleDataConverter.cs
> +    public class ModuleDataConverter : DataConverter
comment

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceDefinitionViewModel.cs
> +        #region Fields
we dont want to use regions

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceDefinitionViewModel.cs
> +        }
move to private methods

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +    /// <summary>
```suggestion
{
    /// <summary>
```

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +        #region Fields
remove regions

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +            this.serviceClient = serviceClient;
```suggestion
        {
            this.serviceClient = serviceClient;
```

2022-03-18 10:25 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Views/ServiceView.xaml.cs
> +            }
```suggestion
            {
                addCardButton.Command = viewModel.AddCardCommand;
            }
```

2022-03-18 13:56 UTC, 4eck-qed commented on src/Simplic.ServicePlatform.UI/Behaviors/CopyItemDragDropBehavior.cs
> +}
yes it is supposed to do nothing in so items wont get removed on drag drop completion.

2022-03-18 14:35 UTC, 4eck-qed commented on src/Simplic.ServicePlatform.UI/Behaviors/UniqueServiceModuleDragDropBehavior.cs
> +                MessageBox.Show(CommonServiceLocator.ServiceLocator.Current.GetInstance<ILocalizationService>().Translate("validation_already_exists", draggedModule?.Model.Name));
Add https://github.com/simplic/simplic-studio/pull/55 to the official package.

2022-03-23 09:23 UTC, FabianFS10 commented
![image](https://user-images.githubusercontent.com/98806534/159666092-a65e3f08-9e4f-420b-a83e-b7f1f659f85d.png)

2022-03-23 10:38 UTC, MEichhoff requested changes

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.Data.DB/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
```suggestion
[assembly: AssemblyVersion("1.1.22.323")]
[assembly: AssemblyFileVersion("1.1.22.323")]
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Converters/ModuleDataConverter.cs
> +    public class ModuleDataConverter : DataConverter
```suggestion
    /// <summary>
    /// Converter for modules to service definitions.
    /// </summary>
    public class ModuleDataConverter : DataConverter
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Converters/NullToBooleanConverter.cs
> +    }
```suggestion
        }
    }
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Converters/NullToBooleanConverter.cs
> +}
```suggestion
    }
}
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.38400.0")]
```suggestion
[assembly: AssemblyVersion("1.0.22.323")]
[assembly: AssemblyFileVersion("1.0.22.323")]
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceDefinitionViewModel.cs
> +        private string CheckServiceName()
```suggestion
        }
        
        private string CheckServiceName()
```

2022-03-23 10:38 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ViewModels/ServiceViewModel.cs
> +        }
```suggestion
            if (errors) LocalizedMessageBox.Show("error_save_services", "Error", MessageBoxButton.OK, MessageBoxImage.Information);
        }
```

2022-03-23 13:31 UTC, MEichhoff commented
![image](https://user-images.githubusercontent.com/26067060/159711070-33c44230-c2af-4bf0-8615-a71ca1f3aa18.png)

2022-03-23 13:37 UTC, MEichhoff commented
also remove the ':' after Dienstname

2022-03-23 15:00 UTC, FabianFS10 commented
![image](https://user-images.githubusercontent.com/98806534/159729540-e7ef1d57-c322-42b2-bd6e-9ed31c933624.png)

2022-03-23 15:20 UTC, MEichhoff commented
the space between the name nad the config can be smaller, also please include a screenshot with an opened configuration

2022-03-23 15:35 UTC, FabianFS10 commented
![image](https://user-images.githubusercontent.com/98806534/159736977-c738ddb1-80eb-401c-a28f-ac62213574e0.png)

2022-03-25 07:35 UTC, MEichhoff commented
still the space between the name and the body can be reduced

2022-03-29 07:15 UTC, FabianFS10 commented
![image](https://user-images.githubusercontent.com/98806534/160554820-469c6b18-7e0d-4814-96c8-ada36247ccc1.png)

2022-03-29 07:16 UTC, FabianFS10 commented
Textbox is now set on stretch, the space was minimal reduced. It has to be like that because of localization the text box has to adjust to the label before the text box.

2022-03-29 07:24 UTC, FabianFS10 commented
![image](https://user-images.githubusercontent.com/98806534/160556653-4ed6a6ef-54b0-41dc-a08c-54d5a177cd42.png)

2022-03-30 08:44 UTC, MEichhoff requested changes

2022-03-30 08:44 UTC, MEichhoff commented on src/Simplic.ServicePlatform.UI/ServicePlattformApplicationHelper.cs
> +        }
```suggestion
            });
        }
```

2022-03-30 09:19 UTC, MEichhoff approved these changes

2022-03-30 09:22 UTC, merged